stages:
- stage: validate
  jobs:
  - job:  validate
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: 'install'
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV3@3
      displayName: 'terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azdevops-spn'
        backendAzureRmResourceGroupName: 'PepsiCo-CTO-EDAP-rg'
        backendAzureRmStorageAccountName: 'rahulteststorageiamokay'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'demo.terraform.tfstate'
    - task: TerraformTaskV3@3
      displayName: 'terraform validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
- stage: deploy
  jobs:
  - deployment: 'deploy_terraform'
    continueOnError: false
    environment: 'dev'
    strategy:
     runOnce:
       deploy:
        steps:
          - checkout: self
          - task: TerraformInstaller@0
            displayName: 'install'
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            displayName: 'terraform init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'azdevops-spn'
              backendAzureRmResourceGroupName: 'PepsiCo-CTO-EDAP-rg'
              backendAzureRmStorageAccountName: 'rahulteststorageiamokay'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'demo.terraform.tfstate'
          - task: TerraformTaskV3@3
            displayName: 'terraform plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'azdevops-spn'
          - task: TerraformTaskV3@3
            displayName: 'terraform apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'azdevops-spn'